### ISSUE TITLE
Updates TODO

### ISSUE THREAD

**Issue by krutisfood** [mrschofield/newcastle-devopsdays#1]
Notes to help me keep track of where we're at :)
*  [x] Link to Newy's code of conduct.
*  [ ] Crop Hailey's photo
*  [x] Hailey's logo doesn't say nib
*  [x] Update (remove) sponsors
*  [x] Add link to sponsorship prospectus!
*  [ ] Update papercall.io to reference our page
*  [ ] Upate ti.to to reference our page
*  [x] Add shout out to Sophie
*  [x] Register & add custom domain devopsdaysnewy.org
*  [x] Replace banner with logo, horizontal words in white?
*  [ ] Update krut gravatar?
